//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitorBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesToWear
    {
        public int ClothID { get; set; }
        public string ClothingItem { get; set; }
        public bool ClothingTop { get; set; }
        public bool ClothingBottom { get; set; }
        public bool ClothingFeet { get; set; }
        public bool Cold { get; set; }
        public bool Warm { get; set; }
        public bool BusinessCasual { get; set; }
        public bool BusinessFormal { get; set; }
        public bool Suit { get; set; }
    }
}
